## Упражнения по библиотеке Numpy

In [44]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [45]:
mas = np.arange(10)
mas[(mas>3) & (mas<8)] *=-1
mas

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

**2.** Заменить максимальный элемент случайного массива на 0

In [46]:
mas = np.random.random(10)
mas[mas==mas.max()] = 0
mas

array([0.72852899, 0.8954206 , 0.        , 0.00575881, 0.0034131 ,
       0.90076203, 0.52189847, 0.72028262, 0.3324747 , 0.15868121])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [47]:
def straight_multiply(arrays):
    arrays = [np.asarray(a) for a in arrays]   
    shape = map(len, arrays)
    
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

straight_multiply([[1, 2, 3], [4, 5], [6, 7]])

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [48]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)
result = []
for ind,arr in enumerate(A):
    fl = True
    for row in B:
        was = False

        for elem in row:
            if elem in arr:
                was = True
                break

        if not was:
            fl = False
            break
    if (fl):
        result.append(ind)

print(result) #тут я не нашел адекватного решения через numpy       

[[4 4 3]
 [2 4 1]
 [4 2 4]
 [0 0 3]
 [0 0 0]
 [1 0 0]
 [0 0 4]
 [0 3 0]]
[[0 1]
 [2 0]]
[1, 3, 4, 5, 6, 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [49]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 3 0]
 [4 3 3]
 [3 1 4]
 [4 1 4]
 [3 0 3]
 [1 0 0]
 [3 0 4]
 [3 1 3]
 [3 1 0]
 [4 3 1]]
[[2 3 0]
 [4 3 3]
 [3 1 4]
 [4 1 4]
 [3 0 3]
 [1 0 0]
 [3 0 4]
 [3 1 3]
 [3 1 0]
 [4 3 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [50]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [1, 2, 3],
                   [7, 8, 9]])

unique_matrix = np.unique(matrix, axis=0)
print(unique_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [51]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

def pyth_def_prod_of_diag(X):
    n,m = X.shape
    i = 0
    result = 1
    while(i<n and i<m):
        if (X[i,i]!=0):
            result*=X[i,i]
        i+=1    
    return result

def numpy_prod_of_diag(X):
    diagonal_elements = np.diagonal(X)
    return np.prod(diagonal_elements[diagonal_elements != 0])


print("python - ",pyth_def_prod_of_diag(X))
print("numpy - ",numpy_prod_of_diag(X))

python -  3
numpy -  3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [53]:
X = np.array([1, 0,4,1])
Y = np.array([0, 1, 4, 1])
def pyth_def_multiset(X,Y):
    count_x = {}
    count_y = {}
    for item in X:
        count_x[item] = count_x.get(item, 0) + 1
    for item in Y:
        count_y[item] = count_y.get(item, 0) + 1

    return count_x == count_y

def numpy_prod__multiset(X,Y):
    unique_x, counts_x = np.unique(X, return_counts=True)
    unique_y, counts_y = np.unique(Y, return_counts=True)
    return np.array_equal(unique_x, unique_y) and np.array_equal(counts_x, counts_y)


print("python - ",pyth_def_multiset(X,Y))
print("numpy - ",numpy_prod__multiset(X,Y))

python -  True
numpy -  True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [62]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

def pyth_def_max_after_0(x):
    max_item = -float('inf')
    for i in range(1,len(x)):
        if (x[i-1]==0 and x[i]>max_item):
            max_item = x[i]
    return max_item        

def numpy_prod_max_after_0(x):
    after_zeros = x[np.where(np.roll(x, 1) == 0)]
    if x[-1]==0:
        if after_zeros.size>1:
            after_zeros[0]= after_zeros[1]
        else:
            return -float('inf')
    return after_zeros.max() if after_zeros.size>0 else -float('inf')


print("python - ",pyth_def_max_after_0(x))
print("numpy - ",numpy_prod_max_after_0(x))

python -  5
numpy -  5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [69]:
x = np.array([2, 2, 2, 3, 3, 3, 5])

def pyth_def_run_length_enc(x):
    count_x = {}
    for item in x:
        count_x[item] = count_x.get(item, 0) + 1
    keys =[]
    counts = []    
    for key, value in count_x.items():
        keys.append(int(key))
        counts.append(value)

    return (keys,counts)  

def numpy_run_length_enc(x):
    return np.unique(x, return_counts=True)


print("python - ",pyth_def_run_length_enc(x))
print("numpy - ",numpy_run_length_enc(x))

python -  ([2, 3, 5], [3, 3, 1])
numpy -  (array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [72]:
import scipy.spatial.distance as distance
import time

np.random.seed(0)
X = np.random.rand(1000, 10)  
Y = np.random.rand(1000, 10)

def numpy_euclidean_distance(X, Y):
    dists = np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :]) ** 2, axis=-1))
    return dists


def python_euclidean_distance(X, Y):
    dists = []
    for x in X:
        row = []
        for y in Y:
            dist = sum((xi - yi) ** 2 for xi, yi in zip(x, y)) ** 0.5
            row.append(dist)
        dists.append(row)
    return dists


def scipy_euclidean_distance(X, Y):
    return distance.cdist(X, Y, 'euclidean')


start_time = time.time()
numpy_dists = numpy_euclidean_distance(X, Y)
numpy_time = time.time() - start_time

start_time = time.time()
python_dists = python_euclidean_distance(X, Y)
python_time = time.time() - start_time

start_time = time.time()
scipy_dists = scipy_euclidean_distance(X, Y)
scipy_time = time.time() - start_time

print("NumPy время выполнения:", numpy_time)
print("Обычный Python время выполнения:", python_time)
print("SciPy время выполнения:", scipy_time)


NumPy время выполнения: 0.08208966255187988
Обычный Python время выполнения: 3.7022950649261475
SciPy время выполнения: 0.005000114440917969


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [2]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [3]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [6]:
average_calories = np.mean(calorie_stats)
average_calories

np.float64(106.88311688311688)

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [9]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [11]:
median_calories = np.median(calorie_stats)
median_calories

np.float64(110.0)

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [21]:
nth_percentile = None
for p in range(1, 101):
    percentile_value = np.percentile(calorie_stats, p)
    print(f"percentile: {percentile_value}")

    if percentile_value > 60:
        nth_percentile = percentile_value
        break  
print(f"The smallest percentile greater than 60 calories is: {nth_percentile} with probability {p}%")


percentile: 50.0
percentile: 50.0
percentile: 55.599999999999994
percentile: 70.0
The smallest percentile greater than 60 calories is: 70.0 with probability 4%


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [27]:

more_calories = (np.sum(calorie_stats > 60) / calorie_stats.size) * 100
print(f"Percentage of cereals with more than 60 calories: {more_calories:.2f}%")


Percentage of cereals with more than 60 calories: 96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [29]:
calorie_std = np.std(calorie_stats)
calorie_std

np.float64(19.35718533390827)

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.


На основании анализа данных о содержании калорий в хлопьях, мы установили, что значительная доля конкурентов предлагает продукты с более чем 60 калориями на порцию. Это создает уникальную возможность для Mycrunch продвигать CrunchieMunchies как более здоровый выбор, подчеркивая его низкое содержание калорий в маркетинговых материалах.